{
 "title": "Main Dashboard",
 "description": "Prometheus Blackbox Exporter Overview",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "30s" },
   { "name": "Microservice", "label": "Microservice", "query": { "query": "label_values(service)" } },
   {
    "name": "DNS",
    "label": "DNS",
    "query": {
     "query": "label_values(probe_http_duration_seconds,env)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod Restart Count (24h)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service, env) (\r\n  changes(probe_success{env=\"$DNS\"}[24h])\r\n) or on(service, env) (0 * probe_success{env=\"$DNS\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Most Unstable Environments (24h)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\r\n  sum by (env) (\r\n    changes(probe_success[24h])\r\n  ) or on(env) (0 * probe_success)\r\n) > 10",
     "legendFormat": "{{env}}/{{service}}"
    }
   ]
  },
  {
   "title": "Global Probe Duration for ${DNS}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{env=~\"$DNS\"}",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Alert Table",
   "type": "table",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 23 },
   "targets": [
    { "expr": "probe_http_status_code != 200", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Environment Bubble Chart",
   "type": "digrich-bubblechart-panel",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 23 },
   "targets": [
    { "expr": "probe_http_status_code", "legendFormat": "__auto" }
   ]
  },
  { "title": "${Microservice} status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }, "repeat": "Microservice" },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{env=~\"$DNS\", service=\"$Microservice\"}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{env=~\"$DNS\", service=\"$Microservice\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{env=~\"$DNS\", service=\"$Microservice\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{env=~\"$DNS\", service=\"$Microservice\"}"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_version{env=~\"$DNS\", service=\"$Microservice\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_ssl{env=~\"$DNS\", service=\"$Microservice\"}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 10, "x": 4, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{env=~\"$DNS\", service=\"$Microservice\"} - time()"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{env=~\"$DNS\", service=\"$Microservice\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{env=~\"$DNS\", service=\"$Microservice\"})"
    }
   ]
  },
  {
   "title": "DB Connection Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hikaricp_connections_max{instance=\"$DNS\", application=\"$Microservice-ms\", pool=\"MsHikariCP\"}",
     "legendFormat": "MsHikariCP Max Conn"
    },
    {
     "expr": "hikaricp_connections_idle{instance=\"$DNS\", application=\"$Microservice-ms\", pool=\"MsHikariCP\"}",
     "legendFormat": "MsHikariCP Idle Conn"
    },
    {
     "expr": "hikaricp_connections_active{instance=\"$DNS\", application=\"$Microservice-ms\", pool=\"MsHikariCP\"}",
     "legendFormat": "MsHikariCP Active Conn"
    },
    {
     "expr": "hikaricp_connections_max{instance=\"$DNS\", application=\"$Microservice-ms\", pool=\"ActivitiHikariCP\"}",
     "legendFormat": "ActivitiHikariCP Max Conn"
    },
    {
     "expr": "hikaricp_connections_idle{instance=\"$DNS\", application=\"$Microservice-ms\", pool=\"ActivitiHikariCP\"}",
     "legendFormat": "ActivitiHikariCP Idle Conn"
    },
    {
     "expr": "hikaricp_connections_active{instance=\"$DNS\", application=\"$Microservice-ms\", pool=\"ActivitiHikariCP\"}",
     "legendFormat": "ActivitiHikariCP Active Conn"
    }
   ]
  },
  {
   "title": "CPU Core Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 43 },
   "targets": [
    {
     "expr": "process_cpu_usage{instance=\"$DNS\", application=\"bpmn-ms\"}\r\n*\r\nsystem_cpu_count{instance=\"$DNS\", application=\"bpmn-ms\"}",
     "legendFormat": "Used CPU (Core)"
    },
    {
     "expr": "system_cpu_count{instance=\"$DNS\", application=\"bpmn-ms\"}",
     "legendFormat": "Max CPU (Core)"
    },
    {
     "expr": "system_cpu_count{instance=\"$DNS\", application=\"bpmn-ms\"}\r\n-\r\n(\r\n  process_cpu_usage{instance=\"$DNS\", application=\"bpmn-ms\"}\r\n  *\r\n  system_cpu_count{instance=\"$DNS\", application=\"bpmn-ms\"}\r\n)",
     "legendFormat": "Free CPU (Core)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 43 },
   "targets": [
    {
     "expr": "sum(jvm_memory_max_bytes{instance=\"$DNS\",application=\"bpmn-ms\",area=\"heap\",id=\"G1 Old Gen\"}) / 1024 / 1024",
     "legendFormat": "Max Heap (MB)"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"$DNS\",application=\"bpmn-ms\",area=\"heap\"}) / 1024 / 1024",
     "legendFormat": "Used Heap (MB)"
    },
    {
     "expr": "(\r\n  sum(jvm_memory_max_bytes{instance=\"$DNS\",application=\"bpmn-ms\",area=\"heap\",id=\"G1 Old Gen\"})\r\n  -\r\n  sum(jvm_memory_used_bytes{instance=\"$DNS\",application=\"bpmn-ms\",area=\"heap\"})\r\n) / 1024 / 1024",
     "legendFormat": "Free Heap (MB)"
    }
   ]
  }
 ]
}